### ISSUE TITLE
metadata file for each manga

### ISSUE THREAD

**Issue by MrPicklePinosaur** [KaratsubaScans/Carrot#8]
in the dir for each manga, also include some sorta `metadata` file that holds information like:
```
title: Girl's Last Tour
original title: 少女終末旅行
author: tkmiz
description: potatoes lul
cover_img: https://...
...
```
and then you can also create some pages to show info about the manga. or maybe have a library page with each manga and you can hover over it to get some info before reading

**Comment by MrPicklePinosaur** [comment]
the format of the meta isnt too important, just use sm thats easy to read - json can work too

**Comment by fairnightzz** [comment]
Is the file a .metadata

**Comment by MrPicklePinosaur** [comment]
doesnt matter

**Comment by fairnightzz** [comment]
I want it to be consistent with other metadata stuff so if u torrent manga, there's nothing u rlly need to change

**Comment by fairnightzz** [comment]
ok looks like theres nothing

**Comment by MrPicklePinosaur** [comment]
wait theres a standard?
